### ISSUE TITLE
Mulitplatform HID

### ISSUE THREAD

**Issue by JohnVeness** [SigmaDolphin/SkylanderEditor#6]
The app currently relies on hid.dll system calls, so is Windows-only.

I am no .NET or HID expert so don't know if these are suitable, but some searching found multi-platform HID libraries you could maybe use instead, such as https://github.com/libusb/hidapi and/or https://github.com/MelbourneDeveloper/Device.Net

I realise you wanted to make your app less reliant on external stuff, so this might be incompatible with that goal, but it would be excellent if this could be looked into at least.

**Comment by SigmaDolphin** [comment]
i looked into your suggestions and one is a C library and the other is a C#.NET one, neither of which can be included in a VB.NET project, the problem here is not finding the correct libraries, but the limitations in VB.NET to access such low level interfaces, as i stated in the previous issue, the functions to access HID devices just don't exist in VB.NET and must be imported from the DLL in the case of Windows (which by the way is VERY convoluted to begin with) and would need to access somewhere else in the case of Linux
if you are up to the task i would be willing to research this along with someone who has access to the environment already

another option would be to use someone else's program just to dump and write the backups like @capull0 's and use mine if you want the GUI

**Comment by JohnVeness** [comment]
OK, understood. I didn't realise VB.NET couldn't interface nicely with a C#.NET library.

I'm happy to use another program to do the dumping and writing and yours as the editor GUI.
